$(document).ready(function(){
    $(window).on('load', function() {
        $('#myModal').modal('show');
    });
    $('.absoluteH').click(function(){
        $('.absoluteH').css("color","red")
    });
    $('.list2').hide();
    $('.list3').hide();
    $('.list4').hide();
    $('.listNew2').hide();
    $('.listNew3').hide();
    $('.listNew4').hide();
    $('.listNew5').hide();
    $('.listNewR2').hide();
    $('.listNewR3').hide();
    $('.listNewA2').hide();
    $('.listNewA3').hide();
    $('.listNewA4').hide();
    $('.showList1').click(function(){
        $('.list2').hide();
        $('.list3').hide();
        $('.list4').hide();
        $('.list1').show();
    });
    $('.showList2').click(function(){
        $('.list1').hide();
        $('.list3').hide();
        $('.list4').hide();
        $('.list2').show();
    });
    $('.showList3').click(function(){
        $('.list1').hide();
        $('.list2').hide();
        $('.list4').hide();
        $('.list3').show();
    });
    $('.showList4').click(function(){
        $('.list1').hide();
        $('.list2').hide();
        $('.list3').hide();
        $('.list4').show();
    });
    $('.showListNew1').click(function(){
        $('.listNew1').show();
        $('.listNew2').hide();
        $('.listNew3').hide();
        $('.listNew4').hide();
        $('.listNew5').hide();
    });
    $('.showListNew2').click(function(){
        $('.listNew2').show();
        $('.listNew1').hide();
        $('.listNew3').hide();
        $('.listNew4').hide();
        $('.listNew5').hide();
    });
    $('.showListNew3').click(function(){
        $('.listNew3').show();
        $('.listNew1').hide();
        $('.listNew2').hide();
        $('.listNew4').hide();
        $('.listNew5').hide();
    });
    $('.showListNew4').click(function(){
        $('.listNew4').show();
        $('.listNew1').hide();
        $('.listNew2').hide();
        $('.listNew3').hide();
        $('.listNew5').hide();
    });
    $('.showListNew5').click(function(){
        $('.listNew5').show();
        $('.listNew1').hide();
        $('.listNew2').hide();
        $('.listNew3').hide();
        $('.listNew4').hide();
    });
    $('.showListNewR1').click(function(){
        $('.listNewR1').show();
        $('.listNewR2').hide();
        $('.listNewR3').hide();
    });
    $('.showListNewR2').click(function(){
        $('.listNewR2').show();
        $('.listNewR1').hide();
        $('.listNewR3').hide();
    });
    $('.showListNewR3').click(function(){
        $('.listNewR3').show();
        $('.listNewR1').hide();
        $('.listNewR2').hide();
    });
    $('.showListNewA1').click(function(){
        $('.listNewA1').show();
        $('.listNewA2').hide();
        $('.listNewA3').hide();
        $('.listNewA4').hide();
    });
    $('.showListNewA2').click(function(){
        $('.listNewA2').show();
        $('.listNewA1').hide();
        $('.listNewA3').hide();
        $('.listNewA4').hide();
    });
    $('.showListNewA3').click(function(){
        $('.listNewA3').show();
        $('.listNewA1').hide();
        $('.listNewA2').hide();
        $('.listNewA4').hide();
    });
    $('.showListNewA4').click(function(){
        $('.listNewA4').show();
        $('.listNewA1').hide();
        $('.listNewA2').hide();
        $('.listNewA3').hide();
    });
});